### ISSUE TITLE
The dataset link is invalid

### ISSUE THREAD

**Issue by KunB-Fighting** [DSaurus/Human4DiT#1]
Thanks for your great work!

I have filled the form and got the download link, however, the Baidu Disk link is invalid, please update it

**Comment by DSaurus** [comment]
@KunB-Fighting ,

Thank you for your reminder! I have updated the link. Could you try it again?

**Comment by xymsh** [comment]
The links for 3D, 4D datasets are still invalid.

**Comment by KunB-Fighting** [comment]
> @KunB-Fighting ,
> 
> Thank you for your reminder! I have updated the link. Could you try it again?

Thanks a lot, I can download it now

**Comment by KunB-Fighting** [comment]
> The links for 3D, 4D datasets are still invalid. 

It is a little bit strangr, i can download it last night

**Comment by xymsh** [comment]
I got it. When I clicked the link, it said "The page doesn't exist". But when I copy the text (not the link), and paste into the browser. It works. Maybe there's an issue with Chrome's redirection.

**Comment by YeeZ93** [comment]
Same issue here, but I still can not get access to the data by ctrl C ctrl V the released links.
The problem reads like this:
![error_downlaods](https://github.com/user-attachments/assets/a30d750c-4bc8-4cbc-ac44-52891b29e3f8)

@DSaurus Could you please have a look at the links ? Thanks in advance!
